### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Thiteago** [Thiteago/svelte-clau-prado#4]
- [x] Added login expiration (improve security)
- [x] Temporary user to improve easy sale
- [x] Better validation on checkout
- [x] Change payment methods to third party
- [x] Flow of expenses
- [x] Make reviews works

**Comment by Thiteago** [comment]
- [ ] FIX: endereco.id is null on pedido create
